# Conteúdo Extra
# Python para Análise de Dados - Numpy   

<p> Iremos aprender a trabalhar coma biblioteca Numpy.


# Acessando Dimensões no Array

In [ ]:
# Importando o Numpy
import numpy as np

In [ ]:
# Gera um array aleatório de 10 linhas e 2 colunas
# formato linha,coluna
my_array = np.random.random([10,2])

In [ ]:
my_array

array([[0.8663725 , 0.59168859],
       [0.20163981, 0.77899362],
       [0.81105069, 0.50584237],
       [0.06515974, 0.75111978],
       [0.02580588, 0.99337326],
       [0.30988847, 0.04408326],
       [0.10581352, 0.94002629],
       [0.09051186, 0.13163383],
       [0.09484018, 0.12952102],
       [0.65278285, 0.08537582]])

In [ ]:
# Imprimindo o primeiro elemento (1 linha)
my_array[0]

array([0.8663725 , 0.59168859])

In [ ]:
# Imprimindo o primeiro elemento da coluna 0 (1 coluna)
my_array[0][0]

0.8663725044994398

In [ ]:
# Primeiro elemento da coluna 1
my_array[0][1]

0.5916885929280624

In [ ]:
# Segundo elemento da coluna 1
my_array[1][1]

0.7789936206121604

In [ ]:
# Segundo elemento da coluna escrito com virgula.
# O primeiro valor especifica a linha e o segundo valor especifica a coluna.
my_array[1,1]

0.7789936206121604

In [ ]:
# Imprimindo até 3 valores da coluna 1
my_array[:3,1]

array([0.59168859, 0.77899362, 0.50584237])

In [ ]:
# Imprime todas as linhas da coluna 2 * 10
my_array[:,1] * 10

array([5.91688593, 7.78993621, 5.05842372, 7.51119778, 9.93373258,
       0.44083261, 9.40026295, 1.31633826, 1.29521022, 0.85375819])

In [ ]:
# Comparação retorna indices
my_array > 0.50

array([[ True,  True],
       [False,  True],
       [ True,  True],
       [False,  True],
       [False,  True],
       [False, False],
       [False,  True],
       [False, False],
       [False, False],
       [ True, False]])

In [ ]:
# Acessando valores por índices
my_array[my_array > 0.50]

array([0.8663725 , 0.59168859, 0.77899362, 0.81105069, 0.50584237,
       0.75111978, 0.99337326, 0.94002629, 0.65278285])

# Carregar Arrays NumPy a partir de arquivos de Texto

In [ ]:
import numpy as np

In [ ]:
# Lendo um arquivo do tipo .txt
dataset = np.loadtxt('dataset_array.txt', delimiter=',')

In [ ]:
dataset.shape

(6,)

In [ ]:
dataset

array([1., 2., 3., 4., 5., 6.])

In [ ]:
# carregando um arquivo dividido em 3 arrays
a, b, c = np.loadtxt('dataset_valores.txt', skiprows=1, unpack=True )

In [ ]:
# Array a
a

array([0.4839, 0.1292, 0.1781, 0.7676, 0.5993])

In [ ]:
# Array B
b

array([0.4536, 0.6875, 0.3049, 0.5801, 0.4357])

In [ ]:
# Array C
c

array([0.3561, 0.6565, 0.8928, 0.2038, 0.741 ])

In [ ]:
# Carrega o arquivo ignorando as 2 primeiras linhas e preenchendo os valores vazio por 0
# Obs: os valores string também são convertidos!!

dataset = np.genfromtxt('dataset_valores_vazio.txt', skip_header=2, filling_values=0)

In [ ]:
# Imprimindo o dataset
dataset

array([[0.4839, 0.4536, 0.3561],
       [0.1292, 0.6875, 0.    ],
       [0.1781, 0.3049, 0.8928],
       [0.    , 0.5801, 0.2038],
       [0.5993, 0.4357, 0.741 ]])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=31152f18-3036-40d1-92d9-59f0bbdc0756' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>